### ISSUE TITLE
Use as a "simulation server"?

### ISSUE THREAD

**Issue by treyzania** [itaibn/hlife#1]
I haven't looked too deeply into this, but would it be difficult to implement it into part of a "game of life" server to send requests and responses to ("set these tiles to be alive", "set these to be dead") and have it report back the simulation in each tick on request? I'm planning on building a web game like Place but with Conway's Game of Life and a naive implementation would be very slow on large worlds.

**Comment by itaibn** [comment]
I don't recommend using this library in other projects. It's in an immature state and poorly documented and I'm not developing it anyone. It doesn't even have a license (although if you want to use it, feel free to use it with an Apache/MIT license like in other Rust libraries). There are more mature Life libraries out there; see [this list](http://www.conwaylife.com/wiki/Category:Software) and in particular [Lifelib](http://www.conwaylife.com/wiki/Lifelib) seems good for general-purpose use.
